### ISSUE TITLE
Wrong String type for params -> type

### ISSUE THREAD

**Issue by nickmelis** [GrapeBaBa/hyperledger-java#1]
Sending the following request to fabric:
`fabricNode.chaincode(
      ChaincodeOpPayload.builder()
      .jsonrpc("2.0")
      .id(1)
      .method("deploy")
      .params(
        ChaincodeSpec.builder().chaincodeID(
          ChaincodeID.builder()
          .path("https://github.com/hyperledger/fabric/blob/master/examples/chaincode/go/chaincode_example01/chaincode_example01.go")
          .name("mycc")
          .build())
        .ctorMsg(ChaincodeInput.builder()
            .function("init").args(Arrays.asList("a", "100", "b", "200")).build())
        .secureContext("jim")
        .type(Type.GOLANG)
        .build())
      .build())
    .subscribe(new Action1<ChaincodeOpResult>() {
      @Override
      public void call(ChaincodeOpResult chaincodeOpResult) {
        System.out.printf("Deploy chaincode result:%s\n", chaincodeOpResult);
      }
    });`

The issue logged on the fabric node is:
`10:18:10.671 [rest] ProcessChaincode -> ERRO 026 Error unmarshalling chaincode request payload: json: cannot unmarshal string into Go value of type protos.ChaincodeSpec_Type
`

The JSON being sent is:
`{
  "jsonrpc": "2.0", 
  "method": "deploy", 
  "params": {
    "type": "1"
    "chaincodeID": {
      "name": "mycc", 
      "path": "https://github.com/hyperledger/fabric/blob/master/examples/chaincode/go/chaincode_example01/chaincode_example01.go"
    }, 
    "ctorMsg": {
      "function": "init",   
      "args": ["a", "100", "b", "200"]
    }, 
    "secureContext": "jim" 
  },
  "id": 1
}
`

The problem is with the type param, it has to be an integer in order to be recognised.

**Comment by GrapeBaBa** [comment]
@nickmelis Please try version 0.1.1
